### ISSUE TITLE
android devices not showing up

### ISSUE THREAD

**Issue by anmac1789** [Gustav-Lindberg/AndroidDrive#2] opened 2022-04-13 22:25 UTC
I have connected my galaxy s8 and LG G3 android phones to my PC and ran your software but no devices are showing up. I have enabled USB debugging on both phones. What can I do ?

**Comment by Gustav-Lindberg** [comment] 2022-04-14 07:53
Duplicate of #1

**Closed by Gustav-Lindberg** 2022-04-14 07:53 UTC
